name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

env:
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/${{github.repository_owner}}
  GITHUB_USER: joasimonson
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  # Project
  PROJECT_FILE: JustPaging.AspNetCore.csproj
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.301'
          #source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        #env:
          #NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build $PROJECT_FILE --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release $PROJECT_FILE
      - name: Publish the package to NuGet Gallery
        run: dotnet nuget push "bin/Release/*.nupkg" --api-key $NUGET_KEY --source $NUGET_FEED --skip-duplicate
      - name: Publish the package to GPR
        run: |
           for f in bin/Release/*.nupkg
           do
             curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GHP_FEED
           done
        shell: bash
