name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.301'
          #source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
        #env:
          #NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build Microsoft.AspNetCore.Mvc.Paging.csproj --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release Microsoft.AspNetCore.Mvc.Paging.csproj
      - name: Publish the package to NuGet Gallery
        run: dotnet nuget push "bin/Release/*.nupkg" --api-key ${{NUGET_ORG_KEY}} --source https://api.nuget.org/v3/index.json
      - name: Publish the package to GPR
        run: |
           for f in bin/Release/*.nupkg
           do
             curl -vX PUT -u "vslee:${{ github.token }}" -F package=@$f https://nuget.pkg.github.com/${{github.repository_owner}}
           done
        shell: bash
